org: otjuso
app: viinamayrakoira
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  Resource: "*"
functions:
  graphql:
    handler: ./src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true